create table BLLI_MEMBER(
	MEMBER_EMAIL VARCHAR2(50) NULL,
	MEMBER_ID VARCHAR2(50) PRIMARY KEY,
	MEMBER_PASSWORD VARCHAR2(50) NULL,
	MEMBER_NAME VARCHAR2(50) NOT NULL,
	MEMBER_RECOMMENDED_BABY NUMBER(2) NOT NULL,
	MEMBER_CONDITION NUMBER(2) NOT NULL,
	ENABLED NUMBER(2) DEFAULT 1,
	AUTHORITY varchar2(10) NOT NULL
)

DROP TABLE BLLI_MEMBER

create table BLLI_MEMBER_AUTH(
	MEMBER_id VARCHAR2(50) NOT NULL,
	AUTHORITY varchar2(10) NOT NULL
)
drop table blli_member_auth
